; EONumber 필요함
; HUD Type 2 차종 - Part Number와 RPCS


[Setup]
COM=COM1
PrinterName=ZDesigner ZD421-203dpi ZPL
Company=BWMW
ProductShortName=C/PAD ASSY
EONumber=KDWS0191
Part4M=J1D1
AorAt=A
ModelNo=27
; HHmmss 포맷이며, 출력물에 RHHmmss00**1 총 12자리 들어감
Sequence=1
LastPrinted=260317
AdditionalInformation=
Scanner=COM3

[MODEL23]
ModelName=NQ5a PE
PartNumber=84701-DW510WK
RPCS=Q057W51D

[MODEL24]
ModelName=NQ5a PE
PartNumber=84701-DW500WK
RPCS=Q057W50D

[MODEL25]
ModelName=
PartNumber=
RPCS=

[MODEL26]
ModelName=
PartNumber=
RPCS=
